### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by cishta** [FrothierNine346/crawler-monster-siren#1]
windows环境下目录/分隔的各个字符串尾不能有空格，但目前有个专辑名称为"The cure " 这会导致 main.py 91行报错，
FileNotFoundError: [Errno 2] No such file or directory: './monster-siren/The cure /info.txt'
我自己将目录中空格替换了能解决该问题

**Comment by FrothierNine346** [comment]
此bug已在该[commit](https://github.com/FrothierNine346/crawler-monster-siren/commit/ded5c15dfa5ef697b0d2ae5a50effcb102dae040)修复，经测试无异常，请确认是否是项目最新版本。

**Comment by cishta** [comment]
我已经收到你的邮件!!
