### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by kayakukun** [FrothierNine346/crawler-monster-siren#2]
您好。爬取至专辑《Best Moments of...》时报错：
FileNotFoundError: [Errno 2] No such file or directory: './monster-siren/Best Moments of.../info.txt'

请问有什么解决办法吗？

**Comment by kayakukun** [comment]
是专辑名里的“...”导致的，在165行、181行结尾添加 .rstrip('.') 后可以运行

**Comment by FrothierNine346** [comment]
这个我早就修复了，但懒得推送。😂
现在已经推了。
因为不想修改官方的名称，解决方案是在以"."结尾的专辑名称后加一个"!"。
